ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-json
    exclude: |
      (?x)^(
        \.vscode/.*\.json
      )$
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.0
  hooks:
  - id: check-dependabot
  - id: check-github-workflows

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.1
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix, --show-fixes]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    additional_dependencies:
    - types-requests

- repo: local
  hooks:
  - id: poetry-update
    name: poetry-update
    entry: bash -c 'poetry update --lock'
    language: system
    types: [python]
    pass_filenames: false

  - id: poetry-export
    name: poetry-export
    entry: bash -c 'poetry export -f requirements.txt -o requirements.txt --without-hashes'
    language: system
    types: [python]
    pass_filenames: false
