name: virtmanager

on:
  [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir poetry==1.8.2
          poetry install --no-interaction --no-ansi
      - name: Lint with ruff
        run: |
          poetry add ruff
          poetry run ruff check . --exclude .venv
      - name: Test with pytest
        run: |
          poetry add pytest pytest-cov
          poetry run pytest -v --cov-report=term .
